'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

const EVENTS = [
  'state:changed',
  'order:detected',
  'order:duplicate',
  'order:similar',
  'clipboard:ignored',
  'tracking:detected',
  'tracking:clipped',
  'orders:imported',
  'browser:state',
  'browser:download',
  'browser:loadstart',
  'browser:loadend',
  'browser:loadfail',
  'sync:progress',
  'image:progress',
  'sync:done',
  'routing:done',
  'reorder:applied',
  'app:notice',
  'ui:open-settings',
  'ui:open-debug',
  'ui:open-history',
];

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('state:get'),
  submitScan: (text, force) => ipcRenderer.invoke('scan:submit', { text, force: !!force }),
  nextOrder: () => ipcRenderer.invoke('order:next'),
  addOrderAnyway: (channel, orderNumber) => ipcRenderer.invoke('order:forceAdd', { channel, orderNumber }),
  reopenRow: (id) => ipcRenderer.invoke('order:open', id),
  openOrderPage: (orderNumber, channel, kind) => ipcRenderer.invoke('order:openExternal', { orderNumber, channel, kind }),
  refreshOrders: () => ipcRenderer.invoke('orders:refresh'),
  moveOrder: (orderNumber, target, force) => ipcRenderer.invoke('orders:move', { orderNumber, target, force: !!force }),
  undo: () => ipcRenderer.invoke('undo'),
  updateRow: (id, fields) => ipcRenderer.invoke('rows:update', { id, fields }),
  substituteRow: (id, sku, qty, note, clear, subFor) => ipcRenderer.invoke('rows:substitute', { id, sku, qty, note, clear: !!clear, subFor: subFor || '' }),
  clearFailedRows: () => ipcRenderer.invoke('rows:clearFailed'),
  deleteRow: (id) => ipcRenderer.invoke('rows:delete', id),
  runSync: (ids) => ipcRenderer.invoke('sync:run', { ids }),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  exportCsv: () => ipcRenderer.invoke('csv:export'),
  openCsvFolder: () => ipcRenderer.invoke('csv:openFolder'),
  chooseCsvFolder: () => ipcRenderer.invoke('csv:chooseFolder'),
  testLinnworks: (creds) => ipcRenderer.invoke('linnworks:test', creds),
  getDebugLog: () => ipcRenderer.invoke('debug:get'),
  getHistory: () => ipcRenderer.invoke('history:get'),
  getStock: () => ipcRenderer.invoke('stock:get'),
  getStockOpenOrders: (sku) => ipcRenderer.invoke('stock:openOrders', { sku }),
  setStockLevel: (sku, level) => ipcRenderer.invoke('stock:set', { sku, level }),
  setStockMin: (stockItemId, level) => ipcRenderer.invoke('stock:setMin', { stockItemId, level }),
  salesQuery: (from, to, force) => ipcRenderer.invoke('sales:query', { from, to, force: !!force }),
  getChannelSkus: (stockItemId) => ipcRenderer.invoke('stock:channelSkus', { stockItemId }),
  stockUnlisted: () => ipcRenderer.invoke('stock:unlisted'),
  dropshipSetPad: (sku, qty) => ipcRenderer.invoke('dropship:setPad', { sku, qty }),
  dropshipRemove: (sku) => ipcRenderer.invoke('dropship:remove', { sku }),
  dropshipStats: () => ipcRenderer.invoke('dropship:stats'),
  reorderApply: (entries) => ipcRenderer.invoke('reorder:apply', { entries }),
  createSku: (payload) => ipcRenderer.invoke('stock:createSku', payload),
  addStockImage: (sku, stockItemId) => ipcRenderer.invoke('stock:addImage', { sku, stockItemId }),
  addStockImageUrl: (sku, stockItemId, url) => ipcRenderer.invoke('stock:addImageUrl', { sku, stockItemId, url }),
  cancelStockImage: () => ipcRenderer.invoke('stock:cancelImage'),
  addStockImageFile: (sku, stockItemId, filePath) => ipcRenderer.invoke('stock:addImage', { sku, stockItemId, filePath }),
  // dropped File -> real path (File.path is gone in modern Electron)
  getDroppedFilePath: (file) => webUtils.getPathForFile(file),
  saveStockImage: (sku, url) => ipcRenderer.invoke('stock:saveImage', { sku, url }),
  returnsLookup: (ref) => ipcRenderer.invoke('returns:lookup', { ref }),
  returnsCreate: (payload) => ipcRenderer.invoke('returns:create', payload),
  returnsList: () => ipcRenderer.invoke('returns:list'),
  returnsEditUnit: (payload) => ipcRenderer.invoke('returns:editUnit', payload),
  returnsDeleteUnit: (payload) => ipcRenderer.invoke('returns:deleteUnit', payload),
  returnsTargets: (sku) => ipcRenderer.invoke('returns:targets', { sku }),
  returnsMappings: () => ipcRenderer.invoke('returns:mappings'),
  returnsMapSet: (baseSku, condition, targetSku) => ipcRenderer.invoke('returns:mapSet', { baseSku, condition, targetSku }),
  returnsMapDelete: (baseSku, condition) => ipcRenderer.invoke('returns:mapDelete', { baseSku, condition }),
  wfsList: () => ipcRenderer.invoke('wfs:list'),
  wfsCreate: (note, items) => ipcRenderer.invoke('wfs:create', { note, items }),
  receivingFinish: (lines, meta) => ipcRenderer.invoke('receiving:finish', { lines, ...(meta || {}) }),
  receivingList: () => ipcRenderer.invoke('receiving:list'),
  chooseReceivingFolder: () => ipcRenderer.invoke('receiving:chooseFolder'),
  browserLayout: (bounds) => ipcRenderer.invoke('browser:layout', bounds),
  browserOpen: (orderNumber, channel, kind) => ipcRenderer.invoke('browser:open', { orderNumber, channel, kind }),
  browserOpenUrl: (url) => ipcRenderer.invoke('browser:open', { url }),
  browserOpenUrl: (url) => ipcRenderer.invoke('browser:open', { url }),
  browserNav: (action) => ipcRenderer.invoke('browser:nav', { action }),
  browserPrint: () => ipcRenderer.invoke('browser:print'),
  copyText: (text) => ipcRenderer.invoke('clipboard:copy', text),
  on: (channel, cb) => {
    if (!EVENTS.includes(channel)) return;
    ipcRenderer.on(channel, (_e, data) => cb(data));
  },
});
