'use strict';
const { contextBridge, ipcRenderer, webUtils, webFrame } = require('electron');

const EVENTS = [
  'state:changed',
  'order:detected',
  'order:duplicate',
  'order:similar',
  'clipboard:ignored',
  'tracking:detected',
  'tracking:clipped',
  'orders:imported',
  'browser:state',
  'browser:zoom',
  'mapping:overlay',
  'browser:download',
  'browser:loadstart',
  'browser:loadend',
  'browser:loadfail',
  'sync:progress',
  'image:progress',
  'sync:done',
  'routing:done',
  'reorder:applied',
  'app:notice',
  'claims:uploaded',
  'ebay:photoUploaded',
  'unlisted:refreshed',
  'ui:open-settings',
  'ui:open-debug',
  'ui:open-history',
];

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('state:get'),
  submitScan: (text, force) => ipcRenderer.invoke('scan:submit', { text, force: !!force }),
  nextOrder: () => ipcRenderer.invoke('order:next'),
  addOrderAnyway: (channel, orderNumber) => ipcRenderer.invoke('order:forceAdd', { channel, orderNumber }),
  reopenRow: (id) => ipcRenderer.invoke('order:open', id),
  openOrderPage: (orderNumber, channel, kind) => ipcRenderer.invoke('order:openExternal', { orderNumber, channel, kind }),
  refreshOrders: () => ipcRenderer.invoke('orders:refresh'),
  moveOrder: (orderNumber, target, force) => ipcRenderer.invoke('orders:move', { orderNumber, target, force: !!force }),
  unparkOrder: (orderNumber) => ipcRenderer.invoke('orders:unpark', { orderNumber }),
  undo: () => ipcRenderer.invoke('undo'),
  updateRow: (id, fields) => ipcRenderer.invoke('rows:update', { id, fields }),
  substituteRow: (id, sku, qty, note, clear, subFor) => ipcRenderer.invoke('rows:substitute', { id, sku, qty, note, clear: !!clear, subFor: subFor || '' }),
  clearFailedRows: () => ipcRenderer.invoke('rows:clearFailed'),
  deleteRow: (id) => ipcRenderer.invoke('rows:delete', id),
  runSync: (ids) => ipcRenderer.invoke('sync:run', { ids }),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  exportCsv: () => ipcRenderer.invoke('csv:export'),
  openCsvFolder: () => ipcRenderer.invoke('csv:openFolder'),
  chooseCsvFolder: () => ipcRenderer.invoke('csv:chooseFolder'),
  testLinnworks: (creds) => ipcRenderer.invoke('linnworks:test', creds),
  getDebugLog: () => ipcRenderer.invoke('debug:get'),
  getHistory: () => ipcRenderer.invoke('history:get'),
  getStock: () => ipcRenderer.invoke('stock:get'),
  getStockOpenOrders: (sku) => ipcRenderer.invoke('stock:openOrders', { sku }),
  setStockLevel: (sku, level) => ipcRenderer.invoke('stock:set', { sku, level }),
  setStockMin: (stockItemId, level) => ipcRenderer.invoke('stock:setMin', { stockItemId, level }),
  salesQuery: (from, to, force) => ipcRenderer.invoke('sales:query', { from, to, force: !!force }),
  getChannelSkus: (stockItemId) => ipcRenderer.invoke('stock:channelSkus', { stockItemId }),
  stockUnlisted: (force) => ipcRenderer.invoke('stock:unlisted', { force: !!force }),
  dropshipSetPad: (sku, qty) => ipcRenderer.invoke('dropship:setPad', { sku, qty }),
  dropshipRemove: (sku) => ipcRenderer.invoke('dropship:remove', { sku }),
  dropshipStats: () => ipcRenderer.invoke('dropship:stats'),
  reorderApply: (entries) => ipcRenderer.invoke('reorder:apply', { entries }),
  createSku: (payload) => ipcRenderer.invoke('stock:createSku', payload),
  addStockImage: (sku, stockItemId) => ipcRenderer.invoke('stock:addImage', { sku, stockItemId }),
  addStockImageUrl: (sku, stockItemId, url) => ipcRenderer.invoke('stock:addImageUrl', { sku, stockItemId, url }),
  cancelStockImage: () => ipcRenderer.invoke('stock:cancelImage'),
  addStockImageFile: (sku, stockItemId, filePath) => ipcRenderer.invoke('stock:addImage', { sku, stockItemId, filePath }),
  // dropped File -> real path (File.path is gone in modern Electron)
  getDroppedFilePath: (file) => webUtils.getPathForFile(file),
  saveStockImage: (sku, url) => ipcRenderer.invoke('stock:saveImage', { sku, url }),
  returnsLookup: (ref) => ipcRenderer.invoke('returns:lookup', { ref }),
  returnsCreate: (payload) => ipcRenderer.invoke('returns:create', payload),
  returnsList: () => ipcRenderer.invoke('returns:list'),
  returnsEditUnit: (payload) => ipcRenderer.invoke('returns:editUnit', payload),
  returnsDeleteUnit: (payload) => ipcRenderer.invoke('returns:deleteUnit', payload),
  returnsTargets: (sku) => ipcRenderer.invoke('returns:targets', { sku }),
  returnsMappings: () => ipcRenderer.invoke('returns:mappings'),
  returnsMapSet: (baseSku, condition, targetSku) => ipcRenderer.invoke('returns:mapSet', { baseSku, condition, targetSku }),
  returnsMapDelete: (baseSku, condition) => ipcRenderer.invoke('returns:mapDelete', { baseSku, condition }),
  shelfGet: (force) => ipcRenderer.invoke('shelf:get', { force: !!force }),
  wfsList: () => ipcRenderer.invoke('wfs:list'),
  wfsCreate: (note, items) => ipcRenderer.invoke('wfs:create', { note, items }),
  receivingFinish: (lines, meta) => ipcRenderer.invoke('receiving:finish', { lines, ...(meta || {}) }),
  receivingList: () => ipcRenderer.invoke('receiving:list'),
  chooseReceivingFolder: () => ipcRenderer.invoke('receiving:chooseFolder'),
  // the native pane is positioned in unzoomed window pixels, but the DOM
  // rect is measured in zoomed CSS pixels — scale here so every caller stays
  // oblivious to the UI zoom level
  browserLayout: (bounds) => {
    const z = webFrame.getZoomFactor() || 1;
    const b = bounds && bounds.visible
      ? { visible: true, x: bounds.x * z, y: bounds.y * z, width: bounds.width * z, height: bounds.height * z }
      : bounds;
    return ipcRenderer.invoke('browser:layout', b);
  },
  // whole-app zoom (Ctrl+scroll): clamped, returned so the caller can persist
  uiZoom: (factor) => {
    const z = Math.min(1.6, Math.max(0.6, Number(factor) || 1));
    webFrame.setZoomFactor(z);
    return z;
  },
  uiZoomGet: () => webFrame.getZoomFactor() || 1,
  browserOpen: (orderNumber, channel, kind) => ipcRenderer.invoke('browser:open', { orderNumber, channel, kind }),
  browserOpenUrl: (url) => ipcRenderer.invoke('browser:open', { url }),
  openExternalUrl: (url) => ipcRenderer.invoke('app:openExternal', { url }),
  appFocus: () => ipcRenderer.invoke('app:focus'),
  shipImport: () => ipcRenderer.invoke('ship:importFile'),
  mappingChannels: () => ipcRenderer.invoke('mapping:channels'),
  mappingItems: (channelId, source, subSource, force) => ipcRenderer.invoke('mapping:items', { channelId, source, subSource, force }),
  mappingLink: (channelSku, source, subSource, targetSku, channelRefId) => ipcRenderer.invoke('mapping:link', { channelSku, source, subSource, targetSku, channelRefId }),
  mappingUnlink: (rowId) => ipcRenderer.invoke('mapping:unlink', { rowId }),
  listingOpen: (sku, channel, external, refId) => ipcRenderer.invoke('listing:open', { sku, channel, external, refId }),
  mappingLinkedSets: () => ipcRenderer.invoke('mapping:linkedSets'),
  stockDeleteSku: (stockItemId, sku) => ipcRenderer.invoke('stock:deleteSku', { stockItemId, sku }),
  stockRenameSku: (stockItemId, oldSku, newSku) => ipcRenderer.invoke('stock:renameSku', { stockItemId, oldSku, newSku }),
  unlistedIgnore: (sku, remove) => ipcRenderer.invoke('stock:unlistedIgnore', { sku, remove }),
  browserPlatformMenu: () => ipcRenderer.invoke('browser:platformMenu'),
  browserNav: (action) => ipcRenderer.invoke('browser:nav', { action }),
  browserZoom: (dir) => ipcRenderer.invoke('browser:zoom', { dir }),
  browserPrint: () => ipcRenderer.invoke('browser:print'),
  ebaySpecs: (baseSku) => ipcRenderer.invoke('ebay:specs', { baseSku }),
  ebayQr: (sku) => ipcRenderer.invoke('ebay:qr', { sku }),
  ebayPhotosPick: () => ipcRenderer.invoke('ebay:photosPick'),
  ebayExport: (listing, photoPaths) => ipcRenderer.invoke('ebay:export', { listing, photoPaths }),
  overviewData: () => ipcRenderer.invoke('overview:data'),
  overviewPhone: () => ipcRenderer.invoke('overview:phone'),
  temuState: () => ipcRenderer.invoke('temu:state'),
  temuTemplate: () => ipcRenderer.invoke('temu:template'),
  temuPackages: (model, pack) => ipcRenderer.invoke('temu:packages', { model, pack }),
  temuTitles: (model, title) => ipcRenderer.invoke('temu:titles', { model, title }),
  titleLookup: (upc, query) => ipcRenderer.invoke('listing:titleLookup', { upc, query }),
  temuExport: (products) => ipcRenderer.invoke('temu:export', { products }),
  claimsInfo: (po) => ipcRenderer.invoke('claims:info', { po: po || '' }),
  claimsOpenFolder: () => ipcRenderer.invoke('claims:openFolder'),
  copyText: (text) => ipcRenderer.invoke('clipboard:copy', text),
  on: (channel, cb) => {
    if (!EVENTS.includes(channel)) return;
    ipcRenderer.on(channel, (_e, data) => cb(data));
  },
});
